"""Deliverables: fix.diff, pr.diff, PR.md (with verifier evidence) or REPORT.md."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from verifier import Baseline

from . import prompts
from . import repo as repo_mod

if TYPE_CHECKING:
    from .agent import Agent, AgentResult, Attempt
    from .github import Issue

LOG_TAIL_LINES = 30


def _tail(path: Path, lines: int = LOG_TAIL_LINES) -> str:
    try:
        text = path.read_text().rstrip().splitlines()
    except OSError:
        return "(log not found)"
    return "\n".join(text[-lines:])


def _counts(counts: dict[str, int]) -> str:
    order = ["passed", "failed", "error", "skipped", "xfailed", "xpassed", "collection_errors"]
    return ", ".join(f"{counts[k]} {k}" for k in order if counts.get(k)) or "no tests"


def _rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def write_pr(agent: "Agent", issue: "Issue", summary: dict, result: "AgentResult", baseline: Baseline,
             accepted: "Attempt", workspace: Path, base: str) -> Path:
    run_dir = agent.run_dir
    (run_dir / "fix.diff").write_text(accepted.patch)

    # pr.diff = verified source fix + the reproducing test as a new file
    repo_mod.reset(workspace, base)
    try:
        repo_mod.git(workspace, "apply", "--whitespace=nowarn", str((run_dir / "fix.diff").resolve()))
        target = workspace / baseline.repro.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(baseline.repro.content)
        pr_diff = repo_mod.diff(workspace)
    finally:
        repo_mod.reset(workspace, base)
    (run_dir / "pr.diff").write_text(pr_diff)

    try:
        text = agent._ask("mid", [
            {"role": "system", "content": prompts.SYSTEM},
            {"role": "user", "content": prompts.pr_summary(issue.title, summary, accepted.patch, accepted.explanation)},
        ])
    except Exception:  # the PR text is cosmetic; never lose a verified fix over it
        text = accepted.explanation or summary.get("summary", "")

    evidence = Path(accepted.evidence_dir)
    verdict = json.loads((evidence / "verdict.json").read_text())
    runs = {r["name"]: r for r in verdict["runs"]}
    base_suite = baseline.suite.counts()
    existing = sorted(baseline.suite.failing())
    heldout = verdict.get("heldout") or {}
    heldout_line = ""
    if heldout:
        passed = sum(1 for o in heldout.values() if o == "passed")
        mode = "required" if agent.settings.heldout_mode == "gate" else "informational"
        before = _counts(baseline.heldout_run.counts()) if baseline.heldout_run else "—"
        heldout_line = f"| Held-out edge-case tests ({mode}) | {before} | {passed}/{len(heldout)} passed |\n"
    flaky = verdict.get("flaky_ignored") or []

    body = f"""Fixes {issue.url or f'{issue.owner}/{issue.repo}#{issue.number}'}

## Summary

{text.strip()}

## Reproducing test

Added `{baseline.repro.path}`, which fails on the original code and passes with this change:

```python
{baseline.repro.content.rstrip()}
```

## Verification

An independent verifier (deterministic code, no LLM) ran every check in a fresh, network-isolated container against a clean checkout of `{base[:12]}`. It applied this patch itself and injected the reproducing test from its own stored copy.

| Check | Before (base commit) | After (this patch) |
|---|---|---|
| Reproducing test | {_counts(_repro_counts(baseline))} | {_counts(_repro_counts_after(evidence, baseline))} |
| Existing test suite | {_counts(base_suite)} | {_counts(runs.get('suite', {}).get('counts', {}))} |
{heldout_line}
- New failures versus baseline: **none**{f" ({len(existing)} test(s) were already failing before this change and are unaffected)" if existing else ""}.
- Patch policy: only source files changed; no test, test-config or CI files; no skip/xfail markers.{f"{chr(10)}- Flaky tests ignored after re-running on the base commit: {', '.join(flaky)}" if flaky else ""}
- Fix attempts: {len(result.fix_attempts)} (rejected attempts and their reasons are in `{_rel(run_dir / 'REPORT.md', run_dir)}`).

<details><summary>Reproducing test output before the fix</summary>

```
{_tail(baseline.evidence_dir / 'targeted.log')}
```
</details>

<details><summary>Reproducing test output after the fix</summary>

```
{_tail(evidence / 'targeted.log', 15)}
```
</details>

<details><summary>Existing suite output after the fix</summary>

```
{_tail(evidence / 'suite.log', 15)}
```
</details>

---
Generated by FixLoop using {_models_line(agent)}. Verdict: `{_rel(evidence / 'verdict.json', run_dir)}`. Please review before merging: passing tests do not guarantee a correct fix.
"""
    path = run_dir / "PR.md"
    path.write_text(body)
    write_failure_report(agent, issue, result, title="Attempt log")
    return path


def _models_line(agent: "Agent") -> str:
    models = sorted(set(agent.settings.models.values()))
    return f"{', '.join(f'`{m}`' for m in models)} on {agent.settings.provider_label}"


def _repro_counts(baseline: Baseline) -> dict[str, int]:
    counts: dict[str, int] = {}
    for t in baseline.targeted.in_file(baseline.repro.path).values():
        counts[t["outcome"]] = counts.get(t["outcome"], 0) + 1
    return counts


def _repro_counts_after(evidence: Path, baseline: Baseline) -> dict[str, int]:
    try:
        report = json.loads((evidence / "targeted.json").read_text())
    except (OSError, ValueError):
        return {}
    counts: dict[str, int] = {}
    for nodeid, t in report.get("tests", {}).items():
        if nodeid.split("::", 1)[0] == baseline.repro.path:
            counts[t["outcome"]] = counts.get(t["outcome"], 0) + 1
    return counts


def write_failure_report(agent: "Agent", issue: "Issue", result: "AgentResult", title: str = "No fix accepted") -> Path:
    lines = [f"# {title}: {issue.owner}/{issue.repo}#{issue.number}", "", f"Issue: {issue.title}", ""]
    if result.relevant_files:
        lines += [f"Relevant files: {', '.join(result.relevant_files)}", ""]
    for a in result.fix_attempts:
        lines += [f"## Attempt {a.number}: {'accepted' if a.accepted else 'rejected'}", ""]
        if a.explanation:
            lines += [f"Model's explanation: {a.explanation}", ""]
        if not a.accepted:
            lines += ["Verifier feedback:", "", "```", a.feedback, "```", ""]
        if a.patch:
            lines += ["```diff", a.patch.rstrip(), "```", ""]
    path = agent.run_dir / "REPORT.md"
    path.write_text("\n".join(lines))
    return path
